
TRUNCATE TABLE PRICE_HISTORY;
TRUNCATE TABLE HANDLED;
TRUNCATE TABLE FEEDBACKS;
TRUNCATE TABLE PRODUCTS_IN_ORDERS;
TRUNCATE TABLE PRODUCTS_IN_SHOPS_1;
TRUNCATE TABLE PRODUCTS_IN_SHOPS_2;
TRUNCATE TABLE COMPLAINTS_ON_SHOPS;
TRUNCATE TABLE COMPLAINTS_ON_ORDERS;
TRUNCATE TABLE COMPLAINTS;
TRUNCATE TABLE ORDERS;
TRUNCATE TABLE PRODUCTS;
TRUNCATE TABLE SHOPS;
TRUNCATE TABLE EMPLOYEES;
TRUNCATE TABLE USERS;