
DROP TABLE PRICE_HISTORY;
DROP TABLE HANDLED;
DROP TABLE FEEDBACKS;
DROP TABLE PRODUCTS_IN_ORDERS;
DROP TABLE PRODUCTS_IN_SHOPS_1;
DROP TABLE PRODUCTS_IN_SHOPS_2;
DROP TABLE COMPLAINTS_ON_SHOPS;
DROP TABLE COMPLAINTS_ON_ORDERS;
DROP TABLE COMPLAINTS;
DROP TABLE ORDERS;
DROP TABLE PRODUCTS;
DROP TABLE SHOPS;
DROP TABLE EMPLOYEES;
DROP TABLE USERS;